update

diff --git a/.script/functions b/.script/functions
--- a/.script/functions
+++ b/.script/functions
@@ -85,6 +85,7 @@ vscode_common_extensions=(
     'DotJoshJohnson.xml'
     'eamodio.gitlens'
     'EditorConfig.EditorConfig'
+    'golang.go'
     'jeff-hykin.better-perl-syntax'
     'LaurentTreguier.rpm-spec'
     'ms-azuretools.vscode-docker'
@@ -110,8 +111,7 @@ vscode_common_extensions=(
     'tamasfe.even-better-toml'
     'vscodevim.vim')
 
-vscode_extensions=(
-    'golang.go')
+vscode_extensions=()
 
 _install_vs_code_from_tar() {
     local tar_file=$1
@@ -192,8 +192,7 @@ EOF
     return 0
 }
 
-vscode_extensions_for_insider=(
-    'golang.go-nightly')
+vscode_extensions_for_insider=()
 
 _install_vs_code_insiders_from_tar() {
     local tar_file=$1
@@ -442,4 +441,38 @@ EOF
     update-desktop-database "${HOME}/.local/share/applications"
 
     return 0
+}
+
+_install_graalvm_from_tar() {
+    local tar_file=$1
+    local target_dir=${2:-"${HOME}/.graalvm"}
+    if [ -z "${tar_file}" ]; then
+        echo "Usage: $0 [TAR_FILE] [TARGET_DIR]?"
+        return 255
+    fi
+
+    if [ -d "${target_dir}" ]; then
+        rm -rf "${target_dir}".old
+        mv "${target_dir}" "${target_dir}".old
+    fi
+    mkdir -p "${target_dir}"
+    tar -C "${target_dir}" -xf "${tar_file}" --strip-components=1 --wildcards 'graalvm-ce-java*'
+    if [ $? -ne 0 ]; then
+        >&2 echo "Can't unpack '${tar_file}' to '${target_dir}'"
+        return 255;
+    fi
+
+    cur_dir=$(pwd)
+    mkdir -p "${target_dir}/export-path"
+    cd "${target_dir}/export-path"
+    for file in "../bin"/j*; do
+        if [ "$(basename ${file})" = js ]; then
+            continue
+        fi
+        ln -s "${file}" .
+    done
+    for file in "../bin"/{keytool,serialver}; do
+        ln -s "${file}" .
+    done
+    cd "${cur_dir}"
 }
